### PR TITLE
Add DRF integration

### PR DESCRIPTION
**Pull request by rixx**

### CODE REVIEW

**Comment by rixx** [comment]
I added two additional features compared to the implementation in pretix (because, well, I kinda needed them). Give me a thumbs-up and I'll add some shallow tests.

**Comment by raphaelm** [comment]
Looks good to me! :+1: Some tests would be great!

**Comment by rixx** [comment]
@raphaelm I added tests and would call the remaining coverage decrease acceptable.

**Comment by raphaelm** [comment]
Thank you! :)

**Pull request merged**
